# load the required packages
library(tidyverse)
library(knitr)
library(tinytex)
library(moderndive)
library(shiny)
library(styler)
library(utils)
library(fivethirtyeight)
library(httr)
library(httpuv)
library(openxlsx)